name: github-hosted-pipeline-on-my-bestfood

on: 
  push:
    branches:
      - master
      - main
      - development
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: My Best Food
        run: echo "My Best Food is Rice and Beans with Plantain"
        shell: bash
  
